## http://localhost:8080/
server : 
  port : 8080
  
spring :
  datasource :
    url :   jdbc:oracle:thin:@localhost:1521/XE
    #url : jdbc:log4jdbc:oracle:thin:@localhost:1521/XE
    username : 
    password : 
    driver-class-name : oracle.jdbc.OracleDriver